# Generated by Django 6.0.3 on 2026-03-20 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habilidad',
            options={'ordering': ['-porcentaje']},
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='resumen',
            new_name='descripcion',
        ),
        migrations.RemoveField(
            model_name='habilidad',
            name='nivel',
        ),
        migrations.AddField(
            model_name='habilidad',
            name='porcentaje',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perfil',
            name='anios_experiencia',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perfil',
            name='clientes_felices',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perfil',
            name='freelance',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='idiomas',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='perfil',
            name='premios',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perfil',
            name='profesion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='perfil',
            name='proyectos_count',
            field=models.IntegerField(default=0),
        ),
    ]
