# Generated by Django 6.0.3 on 2026-03-20 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_habilidad_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habilidad',
            old_name='nombre',
            new_name='nombre_habilidad',
        ),
    ]
