# Generated by Django 6.0.3 on 2026-03-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_nombre_habilidad_nombre_habilidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='motivo',
            field=models.CharField(max_length=50),
        ),
    ]
