# Generated by Django 6.0.3 on 2026-03-22 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_contacto_motivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='correo',
            new_name='correo_remitente',
        ),
        migrations.RenameField(
            model_name='contacto',
            old_name='nombre',
            new_name='nombre_remitente',
        ),
    ]
